[package]
name = "inkjet"
version = "3.0.0"
description = "Create interactive CLIs and execute Markdown with Inkjet"
authors = ["Brandon Kalinowski <brandon@brandonkalinowski.com>"]
repository = "https://github.com/brandonkal/inkjet"
readme = "README.md"
keywords = ["cli", "task", "command", "make", "markdown"]
categories = [
    "command-line-interface",
    "command-line-utilities",
    "development-tools::build-utils",
    "parser-implementations",
]
edition = "2024"
exclude = [
    "inkjet.md",
    ".gitignore",
    "CHANGELOG.md",
    "test/**",
    ".github/**",
    ".devbox",
]
license = "MIT"
build = "build.rs"

[package.metadata.tauri-winres]
OriginalFilename = "inkjet.exe"
LegalCopyright = "© 2024 Brandon Kalinowski"

[lib]
name = "inkjet"
path = "src/lib.rs"

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
strip = true

[dependencies]
pulldown-cmark = { version = "0.13.4", default-features = false }      # https://github.com/raphlinus/pulldown-cmark
regex = "1.12.3"
url = "2.5.8"
clap = { version = "4.6", features = ["string"] }
clap_complete = "4.6"
color-print = "0.3.7"
demand = "2.0.2"
tempfile = "3.23.0"

[dependencies.syntect]
version = "5.3.0"
default-features = false
features = ["default-syntaxes", "default-themes", "regex-onig"]

[dev-dependencies]
assert_cmd = "2.2.2" # https://github.com/assert-rs/assert_cmd
assert_fs = "1.1.4"   # https://github.com/assert-rs/assert_fs
predicates = "3.1.4"  # https://github.com/assert-rs/predicates-rs

[target.'cfg(not(windows))'.dev-dependencies]
rexpect = "0.7.1"

[target.'cfg(windows)'.build-dependencies]
tauri-winres = "0.3.6"

[build-dependencies]
tauri-winres = "0.3.6"
