name: CI

on: [push, pull_request]

jobs:
  test:
    name: windows-test
    runs-on: windows-11
    env:
      NO_COLOR: 1
    steps:
      - uses: actions/checkout@v4
      - name: Fetch dependencies
        run: cargo fetch
      - name: Run tests
        run: cargo test --frozen
  build:
    name: windows-build
    runs-on: windows-11
    env:
      NO_COLOR: 1
    steps:
      - uses: actions/checkout@v4
      - name: Fetch dependencies
        run: cargo fetch
      - name: Build in release mode
        run: cargo build --release --frozen
      - uses: actions/upload-artifact@v3
        id: artifact-upload-step
        with:
          name: inkjet-windows
          path: .\target\release\inkjet.exe
  linux:
    name: linux-test
    runs-on: earthly
    env:
      FORCE_COLOR: 1
      EARTHLY_CI: true
      EARTHLY_ORG: nimbus
      EARTHLY_SATELLITE: nimbus-sat
    steps:
      - uses: actions/checkout@v4
      - name: Earthly build
        run: earthly --ci +coverage
