name: CI

on: [push, pull_request]

jobs:
  test:
    name: windows-test
    runs-on: windows-11
    env:
      NO_COLOR: 1
    steps:
      - uses: actions/checkout@v4
      - name: Fetch dependencies
        run: cargo fetch
      - name: Run tests
        run: cargo test --frozen
  build:
    name: windows-build
    runs-on: windows-11
    env:
      NO_COLOR: 1
    steps:
      - uses: actions/checkout@v4
      - name: Fetch dependencies
        run: cargo fetch
      - name: Build in release mode
        run: cargo build --release --frozen
