name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Fetch dependencies
        run: cargo fetch
      - name: Build in release mode
        run: cargo build --release --frozen

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Add Ruby for a test that requires it
        uses: actions/setup-ruby@master
        with:
          ruby-version: 2.6.x
      - name: Fetch dependencies
        run: cargo fetch
      - name: Build in test mode
        run: cargo build --tests --frozen
      - name: Make inkjet available globally for certain test suites that depend on it
        run: cp ./target/debug/inkjet /usr/share/rust/.cargo/bin
      - name: Run tests
        run: cargo test --frozen

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Verify formatting is correct
        run: cargo fmt --all -- --check
