name: CI

on: [push, pull_request]

jobs:
  build:
    name: windows-build
    runs-on: windows-11
    steps:
      - uses: actions/checkout@v4
      - name: Fetch dependencies
        run: cargo fetch
      - name: Build in release mode
        run: cargo build --release --frozen

  test:
    name: windows-test
    runs-on: windows-11
    env:
      CLICOLOR_FORCE: 1
    steps:
      - uses: actions/checkout@v4
      - name: Fetch dependencies
        run: cargo fetch
      - name: Build in test mode
        run: cargo build --tests --frozen
      - name: Run tests
        run: cargo test --frozen
